version: '3.8'
services:
  postgres_db:
    image: postgres:14-alpine
    container_name: postgres_db
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4321
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  application:
    image: application:latest
    depends_on:
      - postgres_db
    ports:
      - "8085:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 4321

volumes:
  postgres_data:
